<?php

namespace Database\Seeders;

use App\Models\Pais;
use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder
{
    public function run(): void
    {
        foreach ($this->paises() as $index => $pais) {
            Pais::query()->updateOrCreate(
                ['iso2' => $pais[0]],
                [
                    'nome' => $pais[1],
                    'ddi' => $pais[2],
                    'order' => $pais[0] === 'BR' ? 0 : $index + 1,
                    'is_active' => true,
                ],
            );
        }
    }

    /**
     * @return array<int, array{0: string, 1: string, 2: string}>
     */
    private function paises(): array
    {
        return [
            ['BR', 'Brasil', '55'],
            ['AF', 'Afeganistao', '93'],
            ['ZA', 'Africa do Sul', '27'],
            ['AX', 'Aland, Ilhas', '358'],
            ['AL', 'Albania', '355'],
            ['DE', 'Alemanha', '49'],
            ['AD', 'Andorra', '376'],
            ['AO', 'Angola', '244'],
            ['AI', 'Anguilla', '1'],
            ['AQ', 'Antartida', '672'],
            ['AG', 'Antigua e Barbuda', '1'],
            ['SA', 'Arabia Saudita', '966'],
            ['DZ', 'Argelia', '213'],
            ['AR', 'Argentina', '54'],
            ['AM', 'Armenia', '374'],
            ['AW', 'Aruba', '297'],
            ['AU', 'Australia', '61'],
            ['AT', 'Austria', '43'],
            ['AZ', 'Azerbaijao', '994'],
            ['BS', 'Bahamas', '1'],
            ['BD', 'Bangladesh', '880'],
            ['BB', 'Barbados', '1'],
            ['BH', 'Barein', '973'],
            ['BE', 'Belgica', '32'],
            ['BZ', 'Belize', '501'],
            ['BJ', 'Benin', '229'],
            ['BM', 'Bermudas', '1'],
            ['BY', 'Bielorrussia', '375'],
            ['BO', 'Bolivia', '591'],
            ['BQ', 'Bonaire, Santo Eustaquio e Saba', '599'],
            ['BA', 'Bosnia e Herzegovina', '387'],
            ['BW', 'Botsuana', '267'],
            ['BN', 'Brunei', '673'],
            ['BG', 'Bulgaria', '359'],
            ['BF', 'Burkina Faso', '226'],
            ['BI', 'Burundi', '257'],
            ['BT', 'Butao', '975'],
            ['CV', 'Cabo Verde', '238'],
            ['CM', 'Camaroes', '237'],
            ['KH', 'Camboja', '855'],
            ['CA', 'Canada', '1'],
            ['QA', 'Catar', '974'],
            ['KZ', 'Cazaquistao', '7'],
            ['TD', 'Chade', '235'],
            ['CL', 'Chile', '56'],
            ['CN', 'China', '86'],
            ['CY', 'Chipre', '357'],
            ['SG', 'Cingapura', '65'],
            ['CO', 'Colombia', '57'],
            ['KM', 'Comores', '269'],
            ['CG', 'Congo', '242'],
            ['CD', 'Congo, Republica Democratica', '243'],
            ['KP', 'Coreia do Norte', '850'],
            ['KR', 'Coreia do Sul', '82'],
            ['CI', 'Costa do Marfim', '225'],
            ['CR', 'Costa Rica', '506'],
            ['HR', 'Croacia', '385'],
            ['CU', 'Cuba', '53'],
            ['CW', 'Curacao', '599'],
            ['DK', 'Dinamarca', '45'],
            ['DJ', 'Djibuti', '253'],
            ['DM', 'Dominica', '1'],
            ['EG', 'Egito', '20'],
            ['SV', 'El Salvador', '503'],
            ['AE', 'Emirados Arabes Unidos', '971'],
            ['EC', 'Equador', '593'],
            ['ER', 'Eritreia', '291'],
            ['SK', 'Eslovaquia', '421'],
            ['SI', 'Eslovenia', '386'],
            ['ES', 'Espanha', '34'],
            ['US', 'Estados Unidos', '1'],
            ['EE', 'Estonia', '372'],
            ['SZ', 'Essuatini', '268'],
            ['ET', 'Etiopia', '251'],
            ['FJ', 'Fiji', '679'],
            ['PH', 'Filipinas', '63'],
            ['FI', 'Finlandia', '358'],
            ['FR', 'Franca', '33'],
            ['GA', 'Gabao', '241'],
            ['GM', 'Gambia', '220'],
            ['GH', 'Gana', '233'],
            ['GE', 'Georgia', '995'],
            ['GI', 'Gibraltar', '350'],
            ['GD', 'Granada', '1'],
            ['GR', 'Grecia', '30'],
            ['GL', 'Groenlandia', '299'],
            ['GP', 'Guadalupe', '590'],
            ['GU', 'Guam', '1'],
            ['GT', 'Guatemala', '502'],
            ['GG', 'Guernsey', '44'],
            ['GY', 'Guiana', '592'],
            ['GF', 'Guiana Francesa', '594'],
            ['GN', 'Guine', '224'],
            ['GQ', 'Guine Equatorial', '240'],
            ['GW', 'Guine-Bissau', '245'],
            ['HT', 'Haiti', '509'],
            ['HN', 'Honduras', '504'],
            ['HK', 'Hong Kong', '852'],
            ['HU', 'Hungria', '36'],
            ['YE', 'Iemen', '967'],
            ['BV', 'Ilha Bouvet', '47'],
            ['CX', 'Ilha Christmas', '61'],
            ['IM', 'Ilha de Man', '44'],
            ['NF', 'Ilha Norfolk', '672'],
            ['KY', 'Ilhas Cayman', '1'],
            ['CC', 'Ilhas Cocos', '61'],
            ['CK', 'Ilhas Cook', '682'],
            ['FO', 'Ilhas Faroer', '298'],
            ['GS', 'Ilhas Georgia do Sul e Sandwich do Sul', '500'],
            ['HM', 'Ilhas Heard e McDonald', '672'],
            ['FK', 'Ilhas Malvinas', '500'],
            ['MP', 'Ilhas Marianas do Norte', '1'],
            ['MH', 'Ilhas Marshall', '692'],
            ['PN', 'Ilhas Pitcairn', '64'],
            ['SB', 'Ilhas Salomao', '677'],
            ['TC', 'Ilhas Turks e Caicos', '1'],
            ['UM', 'Ilhas Ultramarinas Menores dos EUA', '1'],
            ['VG', 'Ilhas Virgens Britanicas', '1'],
            ['VI', 'Ilhas Virgens dos EUA', '1'],
            ['IN', 'India', '91'],
            ['ID', 'Indonesia', '62'],
            ['IR', 'Ira', '98'],
            ['IQ', 'Iraque', '964'],
            ['IE', 'Irlanda', '353'],
            ['IS', 'Islandia', '354'],
            ['IL', 'Israel', '972'],
            ['IT', 'Italia', '39'],
            ['JM', 'Jamaica', '1'],
            ['JP', 'Japao', '81'],
            ['JE', 'Jersey', '44'],
            ['JO', 'Jordania', '962'],
            ['KI', 'Kiribati', '686'],
            ['KW', 'Kuwait', '965'],
            ['LA', 'Laos', '856'],
            ['LS', 'Lesoto', '266'],
            ['LV', 'Letonia', '371'],
            ['LB', 'Libano', '961'],
            ['LR', 'Liberia', '231'],
            ['LY', 'Libia', '218'],
            ['LI', 'Liechtenstein', '423'],
            ['LT', 'Lituania', '370'],
            ['LU', 'Luxemburgo', '352'],
            ['MO', 'Macau', '853'],
            ['MG', 'Madagascar', '261'],
            ['MY', 'Malasia', '60'],
            ['MW', 'Malawi', '265'],
            ['MV', 'Maldivas', '960'],
            ['ML', 'Mali', '223'],
            ['MT', 'Malta', '356'],
            ['MA', 'Marrocos', '212'],
            ['MQ', 'Martinica', '596'],
            ['MU', 'Mauricio', '230'],
            ['MR', 'Mauritania', '222'],
            ['YT', 'Mayotte', '262'],
            ['MX', 'Mexico', '52'],
            ['MM', 'Mianmar', '95'],
            ['FM', 'Micronesia', '691'],
            ['MZ', 'Mocambique', '258'],
            ['MD', 'Moldavia', '373'],
            ['MC', 'Monaco', '377'],
            ['MN', 'Mongolia', '976'],
            ['ME', 'Montenegro', '382'],
            ['MS', 'Montserrat', '1'],
            ['NA', 'Namibia', '264'],
            ['NR', 'Nauru', '674'],
            ['NP', 'Nepal', '977'],
            ['NI', 'Nicaragua', '505'],
            ['NE', 'Niger', '227'],
            ['NG', 'Nigeria', '234'],
            ['NU', 'Niue', '683'],
            ['NO', 'Noruega', '47'],
            ['NC', 'Nova Caledonia', '687'],
            ['NZ', 'Nova Zelandia', '64'],
            ['OM', 'Oma', '968'],
            ['NL', 'Paises Baixos', '31'],
            ['PW', 'Palau', '680'],
            ['PS', 'Palestina', '970'],
            ['PA', 'Panama', '507'],
            ['PG', 'Papua-Nova Guine', '675'],
            ['PK', 'Paquistao', '92'],
            ['PY', 'Paraguai', '595'],
            ['PE', 'Peru', '51'],
            ['PF', 'Polinesia Francesa', '689'],
            ['PL', 'Polonia', '48'],
            ['PR', 'Porto Rico', '1'],
            ['PT', 'Portugal', '351'],
            ['KE', 'Quenia', '254'],
            ['KG', 'Quirguistao', '996'],
            ['GB', 'Reino Unido', '44'],
            ['CF', 'Republica Centro-Africana', '236'],
            ['CZ', 'Republica Tcheca', '420'],
            ['DO', 'Republica Dominicana', '1'],
            ['RE', 'Reuniao', '262'],
            ['RO', 'Romenia', '40'],
            ['RW', 'Ruanda', '250'],
            ['RU', 'Russia', '7'],
            ['EH', 'Saara Ocidental', '212'],
            ['PM', 'Saint Pierre e Miquelon', '508'],
            ['WS', 'Samoa', '685'],
            ['AS', 'Samoa Americana', '1'],
            ['SM', 'San Marino', '378'],
            ['SH', 'Santa Helena', '290'],
            ['LC', 'Santa Lucia', '1'],
            ['BL', 'Sao Bartolomeu', '590'],
            ['KN', 'Sao Cristovao e Nevis', '1'],
            ['MF', 'Sao Martinho', '590'],
            ['SX', 'Sao Martinho (parte neerlandesa)', '1'],
            ['ST', 'Sao Tome e Principe', '239'],
            ['VC', 'Sao Vicente e Granadinas', '1'],
            ['SC', 'Seicheles', '248'],
            ['SN', 'Senegal', '221'],
            ['SL', 'Serra Leoa', '232'],
            ['RS', 'Servia', '381'],
            ['SY', 'Siria', '963'],
            ['SO', 'Somalia', '252'],
            ['LK', 'Sri Lanka', '94'],
            ['SD', 'Sudao', '249'],
            ['SS', 'Sudao do Sul', '211'],
            ['SE', 'Suecia', '46'],
            ['CH', 'Suica', '41'],
            ['SR', 'Suriname', '597'],
            ['SJ', 'Svalbard e Jan Mayen', '47'],
            ['TH', 'Tailandia', '66'],
            ['TW', 'Taiwan', '886'],
            ['TJ', 'Tajiquistao', '992'],
            ['TZ', 'Tanzania', '255'],
            ['IO', 'Territorio Britanico do Oceano Indico', '246'],
            ['TF', 'Territorios Franceses do Sul', '262'],
            ['TL', 'Timor-Leste', '670'],
            ['TG', 'Togo', '228'],
            ['TK', 'Tokelau', '690'],
            ['TO', 'Tonga', '676'],
            ['TT', 'Trinidad e Tobago', '1'],
            ['TN', 'Tunisia', '216'],
            ['TM', 'Turcomenistao', '993'],
            ['TR', 'Turquia', '90'],
            ['TV', 'Tuvalu', '688'],
            ['UA', 'Ucrania', '380'],
            ['UG', 'Uganda', '256'],
            ['UY', 'Uruguai', '598'],
            ['UZ', 'Uzbequistao', '998'],
            ['VU', 'Vanuatu', '678'],
            ['VA', 'Vaticano', '39'],
            ['VE', 'Venezuela', '58'],
            ['VN', 'Vietna', '84'],
            ['WF', 'Wallis e Futuna', '681'],
            ['ZM', 'Zambia', '260'],
            ['ZW', 'Zimbabue', '263'],
        ];
    }
}
