<!DOCTYPE html>
<html lang="pt-BR"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1">
<title>{{ $ordem->numero_formatado }}</title>
<style>body{margin:0;background:#f3f4f6;color:#1f2937;font:16px system-ui,sans-serif}.wrap{max-width:720px;margin:auto;padding:16px}.card{background:#fff;border-radius:14px;padding:18px;margin-bottom:14px;box-shadow:0 1px 4px #0001}h1{font-size:1.45rem;margin:0 0 8px}.badge{display:inline-block;background:#f59e0b22;color:#92400e;border-radius:99px;padding:5px 10px;font-weight:700}.grid{display:grid;grid-template-columns:1fr 1fr;gap:10px}.muted{color:#6b7280;font-size:.9rem}button,.button{display:inline-block;border:0;border-radius:9px;padding:12px 16px;background:#d97706;color:#fff;font-weight:700;text-decoration:none;margin:4px 0;cursor:pointer}button.danger{background:#b91c1c}button.secondary{background:#fff;color:#374151;border:1px solid #d1d5db}button:disabled{cursor:wait;opacity:.65}input,textarea,select{box-sizing:border-box;width:100%;padding:11px;border:1px solid #d1d5db;border-radius:8px;margin:5px 0 12px}label{font-weight:650}.error{background:#fee2e2;color:#991b1b;padding:10px;border-radius:8px}.ok{background:#dcfce7;color:#166534;padding:10px;border-radius:8px}.modal{width:min(420px,calc(100% - 32px));padding:0;border:0;border-radius:14px;box-shadow:0 20px 50px #0005}.modal::backdrop{background:#11182799}.modal-content{padding:22px}.modal h2{font-size:1.2rem;margin:0 0 8px}.modal p{color:#6b7280;margin:0}.modal-actions{display:flex;justify-content:flex-end;gap:10px;margin-top:22px}.modal-actions button{margin:0}@media(max-width:540px){.grid{grid-template-columns:1fr}.modal-actions{flex-direction:column-reverse}.modal-actions button{width:100%}}</style></head>
<body><main class="wrap">
@if(session('status'))<p class="ok">{{ session('status') }}</p>@endif
@if($errors->any())<div class="error">@foreach($errors->all() as $erro)<div>{{ $erro }}</div>@endforeach</div>@endif
<section class="card"><h1>{{ $ordem->numero_formatado }} — {{ $ordem->tipo->label() }}</h1><span class="badge">{{ $ordem->status->label() }}</span>
<div class="grid"><p><span class="muted">Cliente</span><br>{{ $ordem->cliente->nome }}</p><p><span class="muted">Veículo</span><br>{{ $ordem->veiculo->placa }} — {{ $ordem->veiculo->veiculo }}</p><p><span class="muted">Atendimento</span><br>{{ $ordem->agendado_em?->format('d/m/Y H:i') }}</p><p><span class="muted">Telefone</span><br><a href="tel:{{ preg_replace('/\D+/', '', $ordem->cliente->telefone1) }}">{{ $ordem->cliente->telefone1 }}</a> · <a href="https://wa.me/55{{ preg_replace('/\D+/', '', $ordem->cliente->telefone1) }}">WhatsApp</a></p></div>
<p><span class="muted">Endereço</span><br>{{ $ordem->endereco }}</p><a class="button" target="_blank" href="https://www.google.com/maps/search/?api=1&query={{ urlencode($ordem->localizacao_latitude && $ordem->localizacao_longitude ? $ordem->localizacao_latitude.','.$ordem->localizacao_longitude : $ordem->endereco) }}">Abrir rota</a>
<p><span class="muted">Serviço</span><br>{{ $ordem->descricao }}</p>@if($ordem->observacoes)<p><span class="muted">Observações</span><br>{{ $ordem->observacoes }}</p>@endif</section>

@if($ordem->status === \App\Enums\OrdemServicoStatus::ENVIADA)
<section class="card"><form method="post" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf<button name="acao" value="aceitar">Aceitar OS</button></form>
<form method="post" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf<label>Motivo da rejeição</label><textarea name="motivo" required></textarea><button class="danger" name="acao" value="rejeitar">Rejeitar OS</button></form></section>
@elseif($ordem->status === \App\Enums\OrdemServicoStatus::ACEITA)
<section class="card"><form id="inicio" method="post" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf<input type="hidden" name="acao" value="iniciar"><input id="lat" type="hidden" name="latitude"><input id="lng" type="hidden" name="longitude"><button type="button" onclick="abrirModalInicio()">Iniciar atendimento</button></form></section>
<dialog id="modal-inicio" class="modal">
<div class="modal-content"><h2>Iniciar atendimento?</h2><p>Confirme que você chegou ao local e deseja registrar o início deste atendimento.</p><div class="modal-actions"><button type="button" class="secondary" onclick="fecharModalInicio()">Cancelar</button><button id="confirmar-inicio" type="button" onclick="confirmarInicio()">Confirmar</button></div></div>
</dialog>
@elseif(in_array($ordem->status,[\App\Enums\OrdemServicoStatus::EM_ATENDIMENTO,\App\Enums\OrdemServicoStatus::PENDENTE],true))
<section class="card"><h2>Dados do atendimento</h2>@if($ordem->motivo_pendencia)<p class="error"><strong>Pendência:</strong> {{ $ordem->motivo_pendencia }}</p>@endif
@if($ordem->tipo !== \App\Enums\OrdemServicoTipo::INSTALACAO)<p>IMEI cadastrado: <strong>{{ $ordem->veiculo->rastreador?->imei }}</strong><br>Chip cadastrado: <strong>{{ $ordem->veiculo->rastreador?->chip?->numero_chip }}</strong></p>
<form method="post" enctype="multipart/form-data" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf<label>Descreva a divergência de IMEI ou chip</label><textarea name="observacao" required></textarea><label>Fotos da divergência (opcional)</label><input type="file" name="fotos[]" accept="image/jpeg,image/png,image/webp" multiple><button class="danger" name="acao" value="divergencia">Informar divergência</button></form>@endif
<form method="post" enctype="multipart/form-data" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf
@if($ordem->tipo !== \App\Enums\OrdemServicoTipo::RETIRADA)<label>Rastreador a instalar</label><select name="rastreador_novo_id"><option value="">Sem troca</option>@foreach($rastreadores as $item)<option value="{{ $item->id }}" @selected((int)$ordem->rastreador_novo_id===$item->id)>{{ $item->imei }}</option>@endforeach</select><label>Chip a instalar</label><select name="chip_novo_id"><option value="">Usar chip do rastreador/sem troca</option>@foreach($chips as $item)<option value="{{ $item->id }}" @selected((int)$ordem->chip_novo_id===$item->id)>{{ $item->numero_chip }} — {{ $item->iccid }}</option>@endforeach</select>@endif
@if($ordem->tipo === \App\Enums\OrdemServicoTipo::MANUTENCAO)<label>Resultado</label><select name="resultado_manutencao" required><option value="">Selecione</option><option value="reparo_sem_troca" @selected($ordem->resultado_manutencao==='reparo_sem_troca')>Reparo sem troca</option><option value="troca_rastreador" @selected($ordem->resultado_manutencao==='troca_rastreador')>Troca do rastreador</option><option value="troca_chip" @selected($ordem->resultado_manutencao==='troca_chip')>Troca do chip</option><option value="troca_rastreador_chip" @selected($ordem->resultado_manutencao==='troca_rastreador_chip')>Troca do rastreador e chip</option><option value="sem_defeito" @selected($ordem->resultado_manutencao==='sem_defeito')>Equipamento sem defeito</option></select><label>Serviço ou diagnóstico</label><textarea name="descricao_atendimento" required>{{ $ordem->descricao_atendimento }}</textarea>@endif
@if($ordem->tipo !== \App\Enums\OrdemServicoTipo::INSTALACAO)<label><input style="width:auto" type="checkbox" name="equipamentos_confirmados" value="1" @checked($ordem->equipamentos_confirmados) required> Confirmo que IMEI e chip correspondem ao cadastro</label><br><br>@endif
<label>Fotos (máximo de 4, até 5 MB cada)</label><input type="file" name="fotos[]" accept="image/jpeg,image/png,image/webp" multiple {{ $ordem->fotos->isEmpty() ? 'required' : '' }}>
<button name="acao" value="conferencia">Solicitar conferência</button></form></section>
@elseif($ordem->status === \App\Enums\OrdemServicoStatus::AGUARDANDO_CORRECAO_CADASTRAL)<section class="card"><p>A central foi avisada da divergência cadastral. Aguarde a correção para continuar.</p></section>
@elseif($ordem->status === \App\Enums\OrdemServicoStatus::EM_CONFERENCIA)<section class="card"><p>Atendimento enviado. A central está realizando a conferência.</p></section>@endif
@if($ordem->status === \App\Enums\OrdemServicoStatus::FINALIZADA)<section class="card"><h2>Atendimento concluído</h2><p><span class="muted">Início real</span><br>{{ $ordem->iniciada_em?->format('d/m/Y H:i') }}</p><p><span class="muted">Término técnico</span><br>{{ $ordem->termino_tecnico_em?->format('d/m/Y H:i') }}</p><p><span class="muted">Finalização administrativa</span><br>{{ $ordem->finalizada_em?->format('d/m/Y H:i') }}</p>@if($ordem->descricao_atendimento)<p><span class="muted">Serviço ou diagnóstico</span><br>{{ $ordem->descricao_atendimento }}</p>@endif @if($ordem->tipo !== \App\Enums\OrdemServicoTipo::RETIRADA)<p>Funcionamento: {{ $ordem->check_funcionamento?'Conferido':'—' }}<br>Pós-chave: {{ $ordem->check_pos_chave?'Conferido':'—' }}<br>Bloqueio: {{ $ordem->check_bloqueio==='nao_se_aplica'?'Não se aplica':'Conferido' }}</p>@endif</section>@endif
@if($ordem->fotos->isNotEmpty())<section class="card"><h2>Fotos</h2>@foreach($ordem->fotos as $foto)<div><a href="{{ route('ordens-servico.tecnico.foto',[$token,$foto]) }}" target="_blank">{{ $foto->nome_original ?: 'Foto '.$loop->iteration }}</a>@if(in_array($ordem->status,[\App\Enums\OrdemServicoStatus::EM_ATENDIMENTO,\App\Enums\OrdemServicoStatus::PENDENTE],true))<form style="display:inline" method="post" action="{{ route('ordens-servico.tecnico.action',$token) }}">@csrf<input type="hidden" name="foto_id" value="{{ $foto->id }}"><button class="danger" style="padding:5px 8px" name="acao" value="remover_foto">Remover</button></form>@endif</div>@endforeach</section>@endif
<section class="card"><h2>Histórico</h2>@foreach($ordem->historicos as $evento)<p><strong>{{ ucfirst(str_replace('_',' ',$evento->evento)) }}</strong><br><span class="muted">{{ $evento->created_at?->format('d/m/Y H:i') }}@if($evento->observacao) · {{ $evento->observacao }}@endif</span></p>@endforeach</section>
</main><script>function abrirModalInicio(){document.getElementById('modal-inicio')?.showModal()}function fecharModalInicio(){document.getElementById('modal-inicio')?.close()}function confirmarInicio(){const f=document.getElementById('inicio'),botao=document.getElementById('confirmar-inicio');botao.disabled=true;botao.textContent='Iniciando...';const enviar=()=>f.submit();if(navigator.geolocation){navigator.geolocation.getCurrentPosition(p=>{document.getElementById('lat').value=p.coords.latitude;document.getElementById('lng').value=p.coords.longitude;enviar()},enviar,{timeout:5000})}else enviar()}</script></body></html>
